---

- hosts: all
  become: true
  tasks:

  - name: updare repository index
    apt: 
      update_cache: yes

  - name: install apache2 package
    apt: 
      name: apache2 
  
  - name: add php for apache
    apt: 
      name: libapache2-mod-php
